language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r AWS-springboo2-webservice2 *
  - mkdir -p deploy
  - mv AWS-springboo2-webservice2.zip deploy/AWS-springboo2-webservice2.zip
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: sungmin-springboot-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl : private
    local_dir: deploy
    wait-until-deployed: true
    
# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - pege92@gmail.com
